version: '3.8'
services:
  db:
    image: postgres:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - POSTGRES_DATABASE=genes_selection
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgres
volumes:
  db:
    driver: local